services:
  mongo-1:
    container_name: mongo-1
    image: mongo
    ports:
      - "27017:27017"
    networks:
      "drymcash":
          aliases:
            - mongo-1
    command:
      mongod --replSet drym-replica-set


  mongo-2:
    container_name: mongo-2
    image: mongo
    ports:
      - "27018:27017"
    networks:
      "drymcash":
          aliases:
            - mongo-2
    command:
      mongod --replSet drym-replica-set


  mongo-3:
    container_name: mongo-3
    image: mongo
    ports:
      - "27019:27017"
    networks:
      "drymcash":
        aliases:
          - mongo-3
    command:
      mongod --replSet drym-replica-set


#  init-machine:
#    container_name: init-machine
#    image: mongo
#    depends_on:
#      - mongo-1
#      - mongo-2
#      - mongo-3
#    ports:
#      - "27020:27017"
#    networks:
#      "ajan":
#        aliases:
#          - init-machine
#    command: >
#      mongo --host mongo-1 --eval "rs.initiate({ _id: 'drym-replica-set', members: [{_id: 0, host: 'mongo-1'},{_id: 1, host: 'mongo-2'},{_id: 2, host: 'mongo-3'}]})"

networks:
  # The presence of these objects is sufficient to define them
  drymcash: